// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://bwrlnjtsunrwreimccec.supabase.co"
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3cmxuanRzdW5yd3JlaW1jY2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3Nzc1ODIsImV4cCI6MjA2NjM1MzU4Mn0.XOKQKUeus-Sxt2eYrwt9deggFq1bb7oc6LykLL8fvjc"

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY)